app/account/urls.py
from django.urls import path

from account.views import SignUpView, UserActivationView, ProfileView

app_name = 'account'

urlpatterns = [
   path('signup/', SignUpView.as_view(), name='signup'),
   path('activate/<uuid:username>', UserActivationView.as_view(), name='activate'),
   path("auth/profile/", ProfileView.as_view(), name='profile'),

]

app/currency/api/urls.py
from rest_framework.routers import DefaultRouter

from currency.api.views import (
    RatesViewSet
)

app_name = 'currency_api'

router = DefaultRouter(trailing_slash=False)
router.register('rates/', RatesViewSet, basename='rates')

urlpatterns = [
] + router.urls

app/currency/urls.py
from django.urls import path

from currency.views import (
    RateListView, RateCreateView, RateUpdateView, RateDetailView, RateDeleteView,
    ContactListView, ContactCreateView, ContactUpdateView, ContactDeleteView, ContactDetailView,
    SourceListView, SourceCreateView, SourceUpdateView, SourceDeleteView, SourceDetailView,
    RequestResponseLogView,
)

app_name = 'currency'

urlpatterns = [
    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
    path('contact/list/', ContactListView.as_view(), name='contact-list'),
    path('contact/create/', ContactCreateView.as_view(), name='contact-create'),
    path('contact/update/<int:pk>', ContactUpdateView.as_view(), name='contact-update'),
    path('contact/delete/<int:pk>', ContactDeleteView.as_view(), name='contact-delete'),
    path('contact/details/<int:pk>', ContactDetailView.as_view(), name='contact-detail'),
    path('source/list/', SourceListView.as_view(), name='source-list'),
    path('source/create/', SourceCreateView.as_view(), name='source-create'),
    path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
    path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),
    path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source-detail'),
    path('request/response/log', RequestResponseLogView.as_view(), name='request-response-log'),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import include, path
from currency.views import IndexView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
]


urlpatterns = [
    path('admin/', admin.site.urls),

    path("auth/", include('django.contrib.auth.urls')),

    path("__debug__/", include("debug_toolbar.urls")),

    path('currency/', include('currency.urls')),
    path('account/', include('account.urls')),
    path('api/currency/', include('currency.api.v1.urls')),
    path('api/account/', include('account.api.v1.urls')),


    path('api/swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('api/swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('', IndexView.as_view(), name='index'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/(<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_complete'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/currency/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from currency.choices import RateCurrencyChoices


class Rate(models.Model):
    buy = models.DecimalField(_('Buy'), max_digits=6, decimal_places=2)
    sell = models.DecimalField(_('Sell'), max_digits=6, decimal_places=2)
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    currency = models.PositiveSmallIntegerField(
        _('Currency'),
        choices=RateCurrencyChoices.choices,
        default=RateCurrencyChoices.USD)
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE, related_name='rates')

    class Meta:
        verbose_name = _('Rate')
        verbose_name_plural = _('Rates')


class ContactUs(models.Model):
    email_from = models.EmailField(_('Email from'), blank=False)
    subject = models.CharField(_('Subject'), max_length=25)
    message = models.CharField(_('Message'), max_length=250)

    class Meta:
        verbose_name = _('Contact us')
        verbose_name_plural = _('Contact us')


def source_logo(instance, filename):
    return f"source/logos/{instance.name}/{filename}"


class Source(models.Model):
    source_url = models.CharField(_('Source url'), max_length=255)
    name = models.CharField(_('Name'), max_length=64)
    code_name = models.CharField(_('Code name'), max_length=38, unique=True)
    logo = models.FileField(
        _('Logo'), default=None, null=True, blank=True, upload_to=source_logo
    )

    class Meta:
        verbose_name = _('Source')
        verbose_name_plural = _('Sources')

    def __str__(self):
        return self.name


class RequstResponseLog(models.Model):
    path = models.CharField(_('Path'), max_length=185)
    request_method = models.CharField(_('Request method'), max_length=50, default="GET")
    time = models.DecimalField(_('Time'), max_digits=4, decimal_places=2)
    created = models.DateTimeField(_("Created"), auto_now_add=True)

    class Meta:
        verbose_name = _("Request Respose Log")
        verbose_name_plural = _("Request Respose Logs")

app/currency/forms.py
from django import forms

from currency.models import Rate, ContactUs, Source


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'buy',
            'sell',
            'currency',
            'source'
        )


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'email_from',
            'subject',
            'message'
        )


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            'source_url',
            'name',
            'logo'
        )

app/currency/api/v1/views.py
from rest_framework import viewsets, generics
from rest_framework.renderers import JSONRenderer
from rest_framework_xml.renderers import XMLRenderer
from rest_framework_yaml.renderers import YAMLRenderer

from django_filters import rest_framework as filters
from rest_framework import filters as rest_framework_filters

from currency.models import Rate, Source, ContactUs
from currency.api.v1.serializers import (RateSerializer, SourceSerializer, ContactSerializer)
from currency.api.v1.paginations import DefaultPagination
from currency.api.v1.filters import RateFilter, ContactFilter


class RatesViewSet(viewsets.ModelViewSet):
    queryset = Rate.objects.all().order_by('-created')
    serializer_class = RateSerializer
    renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = DefaultPagination
    filter_backends = (
        filters.DjangoFilterBackend,
        rest_framework_filters.OrderingFilter,
    )
    filterset_class = RateFilter
    ordering_fields = ('buy', 'sell', 'created')


class SourcesViewSet(viewsets.ModelViewSet):
    queryset = Source.objects.all()
    serializer_class = SourceSerializer


class ContactsViewSet(viewsets.ModelViewSet):
    queryset = ContactUs.objects.all().order_by('-id')
    serializer_class = ContactSerializer
    pagination_class = DefaultPagination
    filter_backends = (
        filters.DjangoFilterBackend,
        rest_framework_filters.OrderingFilter,
    )
    filterset_class = ContactFilter
    ordering_fields = ('email_from', 'subject', 'message')


class ContactDetailApiView(generics.RetrieveDestroyAPIView):
    serializer_class = ContactSerializer
    queryset = ContactUs.objects.all()


class SourceDetailApiView(generics.RetrieveDestroyAPIView):
    serializer_class = SourceSerializer
    queryset = Source.objects.all()

app/currency/api/views.py
from rest_framework import viewsets
from rest_framework.renderers import JSONRenderer
from rest_framework_xml.renderers import XMLRenderer
from rest_framework_yaml.renderers import YAMLRenderer

from currency.models import Rate
from currency.api.serializers import RateSerializer


class RatesViewSet(viewsets.ModelViewSet):
    queryset = Rate.objects.all().order_by('-created')
    serializer_class = RateSerializer
    renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)

app/currency/views.py
from currency.filters import ContactUsFilter, RateFilter, SourceFilter
from currency.forms import ContactForm, RateForm, SourceForm
from currency.models import ContactUs, Rate, RequstResponseLog, Source
from currency.tasks import send_email_to_background
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)
from django_filters.views import FilterView


class RateListView(FilterView):
    paginate_by = 10
    queryset = Rate.objects.all().select_related('source')
    filterset_class = RateFilter
    template_name = 'rate_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['filter_params'] = '&'.join(
            f'{key}={value}' for key, value in self.request.GET.items()
            if key != 'page')
        return context


class RateCreateView(UserPassesTestMixin, CreateView):
    form_class = RateForm
    template_name = 'rate_create.html'
    success_url = reverse_lazy('currency:rate-list')

    def test_func(self):
        return self.request.user.is_superuser


class RateUpdateView(UserPassesTestMixin, UpdateView):
    model = Rate
    form_class = RateForm
    template_name = 'rate_update.html'
    success_url = reverse_lazy('currency:rate-list')

    def test_func(self):
        return self.request.user.is_superuser


class RateDetailView(DetailView):
    model = Rate
    template_name = 'rate_details.html'


class RateDeleteView(UserPassesTestMixin, DeleteView):
    model = Rate
    template_name = 'rate_delete.html'
    success_url = reverse_lazy('currency:rate-list')

    def test_func(self):
        return self.request.user.is_superuser


class ContactListView(FilterView):
    paginate_by = 10
    filterset_class = ContactUsFilter
    queryset = ContactUs.objects.all()
    template_name = 'contact.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['filter_params'] = '&'.join(
            f'{key}={value}' for key, value in self.request.GET.items()
            if key != 'page')
        return context


class ContactCreateView(CreateView):
    form_class = ContactForm
    template_name = 'contact_create.html'
    success_url = reverse_lazy('currency:contact-list')

    def _send_mail(self):
        subject = "User Contact Us"
        message = f'''
        Email_from: {self.object.email_from},
        Subject: {self.object.subject},
        Message: {self.object.message}
    '''

        send_email_to_background.apply_async(
            kwargs={
                'subject': subject,
                'message': message
            },
            countdown=10
        )

    def form_valid(self, form):
        redirect = super().form_valid(form)
        self._send_mail()
        return redirect


class ContactUpdateView(UpdateView):
    model = ContactUs
    form_class = ContactForm
    template_name = 'contact_update.html'
    success_url = reverse_lazy('currency:contact-list')


class ContactDeleteView(DeleteView):
    model = ContactUs
    template_name = 'contact_delete.html'
    success_url = reverse_lazy('currency:contact-list')


class ContactDetailView(DetailView):
    model = ContactUs
    template_name = 'contact_details.html'


class SourceListView(FilterView):
    paginate_by = 10
    filterset_class = SourceFilter
    queryset = Source.objects.all()
    template_name = 'source_list.html'


class SourceCreateView(CreateView):
    form_class = SourceForm
    template_name = 'source_create.html'
    success_url = reverse_lazy('currency:source-list')


class SourceUpdateView(UpdateView):
    model = Source
    form_class = SourceForm
    template_name = 'source_update.html'
    success_url = reverse_lazy('currency:source-list')


class SourceDeleteView(DeleteView):
    model = Source
    template_name = 'source_delete.html'
    success_url = reverse_lazy('currency:source-list')


class SourceDetailView(DetailView):
    model = Source
    template_name = 'source_details.html'


class RequestResponseLogView(ListView):
    model = RequstResponseLog
    template_name = 'request_response_log.html'


class IndexView(TemplateView):
    template_name = 'index.html'

# def api_rate(queriset):
#     import json
#     objects = Rate.objects.all()
#     object_list = []
#     for obj in objects:
#         object_list.append({
#             'id': obj.id,
#             'buy': float(obj.buy),
#             'sell': float(obj.sell)
#         })
#     return HttpResponse(json.dumps(object_list), content_type='application/json')

app/currency/templates/contact.html
{% extends 'base.html' %}
{% block title %}
    Contact Us
{% endblock title %}

{% block content %}
<p>
  <div class="btn-group">
   <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" data-display="static" aria-expanded="false">
     Filter
   </button>
   <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
     <form class="btn btn-secondary dropdown-toggle" method="get">
       {{ filter.form.as_p }}
       <button class="dropdown-item" type="submit" >Submit</button>
     </form>
   </div>
 </div>
 </p>
<div class="row">
   <p>
   <a href="{% url 'currency:contact-create' %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Create</a>
   </p>
</div>
<div class="row">
<table class="table table-dark">
   <thead>
     <tr>
       <th scope="col">ID</th>
       <th scope="col">Email from</th>
       <th scope="col">Subject</th>
       <th scope="col">Message</th>
     </tr>
   </thead>
   <tbody>
   {% for contact in contactus_list %}
     <tr>
       <td>{{ contact.id }}</td>
       <td>{{ contact.email_from }}</td>
       <td>{{ contact.subject }}</td>
       <td>{{ contact.message }}</td>
       <td><div class="dropdown">
         <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
           Dropdown
         </button>
         <div class="dropdown-menu">
           <button class="dropdown-item" type="button"><a href="{% url 'currency:contact-update' contact.id %}">Edit</a></button>
           <button class="dropdown-item" type="button"><a href="{% url 'currency:contact-delete' contact.id %}">Delete</a></button>
           <button class="dropdown-item" type="button"><a href="{% url 'currency:contact-detail' contact.id %}">Details</a></button>
         </div>
       </div>
      </td>
     </tr>
   {% endfor %}
   </tbody>
 </table>
</div>
<div>
  {% include 'includes/pagination.html' %}
</div>
{% endblock content %}

app/currency/templates/contact_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  Conact us create
{% endblock %}

{% block content %}
Create Contact us Form
  
  <form class="my-class" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button>Submit</button>
  </form>
{% endblock %}

app/currency/templates/contact_delete.html
{% extends 'base.html' %}

{% block title %}
  Contact delete
{% endblock %}

{% block content %}
Are you sure you want to delete contact with id: {{ object.id }}?
  
  <form method="post">
    {% csrf_token %}
    <button>Delete</button>
  </form>
{% endblock %}

app/currency/templates/contact_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  Contact update
{% endblock %}

{% block content %}
Update Contact us Form
  
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button>Submit</button>
  </form>
{% endblock %}

app/currency/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index
{% endblock title %}
<div class="container">
{% block content %}
    <h1>Hello, Index View!</h1>
{% endblock content %}
</div>

app/currency/templates/rate_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  Rate create
{% endblock %}

{% block content %}
Create Rate Form
  
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button>Submit</button>
  </form>
{% endblock %}

app/currency/templates/rate_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete Rate
{% endblock title %}

{% block content %}
    Are you sure you want to delete rate with id: {{ object.id }}?

    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete!</button>
    </form>

{% endblock content %}

app/currency/templates/rate_list.html
{% extends 'base.html' %}

{% block title %}
    Rate list 
{% endblock title %}

{% block content %}
<p>
  <div class="btn-group">
   <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" data-display="static" aria-expanded="false">
     Filter
   </button>
   <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
     <form class="btn btn-secondary dropdown-toggle" method="get">
       {{ filter.form.as_p }}
       <button class="dropdown-item" type="submit" >Submit</button>
     </form>
   </div>
 </div>
 </p>
<div class="row">
    <p>
    {% if request.user.is_authenticated %}
        <a href="{% url 'currency:rate-create' %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Create</a>
    {% endif %}    
    </p>
 </div>

 <div class="row">
 <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Sell</th>
        <th scope="col">Buy</th>
        <th scope="col">Created</th>
        <th scope="col">Currency</th>
        <th scope="col">Source</th>
      </tr>
    </thead>
    <tbody>
        {% for rate in rate_list %}
      <tr>
        <td>{{ rate.id }}</td>
        <td>{{ rate.sell }}</td>
        <td>{{ rate.buy }}</td>
        <td>{{ rate.created }}</td>
        <td>{{ rate.get_currency_display }}</td>
        <td>{{ rate.source }}</td>
        <td><div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
            Dropdown
          </button>
          <div class="dropdown-menu">
            <button class="dropdown-item" type="button"><a href="{% url 'currency:rate-update' rate.id %}">Edit</a></button>
            <button class="dropdown-item" type="button"><a href="{% url 'currency:rate-delete' rate.id %}">Delete</a></button>
            <button class="dropdown-item" type="button"><a href="{% url 'currency:rate-details' rate.id %}">Details</a></button>
          </div>
        </div>
       </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
 </div>

<div class="row">
  <div class="col-12">
    {% include 'includes/pagination.html' %}
  </div>

</div>
{% endblock content %}

app/currency/templates/rate_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  Rate update
{% endblock %}

{% block content %}
Create Rate Form
  
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button>Submit</button>
  </form>
{% endblock %}

app/currency/templates/request_response_log.html
{% extends 'base.html' %}
{% block title %}
    Request response log
{% endblock title %}

{% block content %}
    Request response log
      {% for request in request_response_log %}
         <tr>
            <td>Id: {{ request.id }}</td>
            <td>Path: {{ request.path }}</td>
            <td>Request Method: {{ request.request_method }}</td>
            <td>Time: {{ request.time }}</td>
         </tr>
      {% endfor %}
   </table>
   

{% endblock content %}

app/currency/templates/source_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
  Source create
{% endblock %}

{% block content %}
<p>
  <img class="logo" src="{% static 'logo/logo.jpg' %}" alt="avatar" height="200px" width="800px">
</p>
Create Source Form
  
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button>Submit</button>
  </form>
{% endblock %}

app/currency/templates/source_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Source Details
{% endblock title %}

{% block content %}
   <p>
    <img class="logo" src="{% static 'logo/logo.jpg' %}" alt="avatar" height="200px" width="800px">
   </p>
        Id: {{ source.id }} <br>
        Source url: {{ source.source_url }} <br>
        Name: {{ source.name }}<br>
{% endblock content %}

app/currency/templates/source_list.html
{% extends 'base.html' %}

{% block title %}
  Source list
{% endblock title %}

{% block content %}
<p>
  <div class="btn-group">
   <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" data-display="static" aria-expanded="false">
     Filter
   </button>
   <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
     <form class="btn btn-secondary dropdown-toggle" method="get">
       {{ filter.form.as_p }}
       <button class="dropdown-item" type="submit" >Submit</button>
     </form>
   </div>
 </div>
 </p>
<div class="row">
    <p>
        <a href="{% url 'currency:source-create' %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Create</a>   
    </p>
 </div>
 <div class="row">
 <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Source url</th>
        <th scope="col">Name</th>
      </tr>
    </thead>
    <tbody>
       {% for src in source_list %}
      <tr>
        <td>{{ src.id }}</td>
        <td>{{ src.source_url }}</td>
        <td>{{ src.name }}</td>
        <td><div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
            Dropdown
          </button>
          <div class="dropdown-menu">
            <button class="dropdown-item" type="button"><a href="{% url 'currency:source-update' src.id %}">Edit</a></button>
            <button class="dropdown-item" type="button"><a href="{% url 'currency:source-delete' src.id %}">Delete</a></button>
            <button class="dropdown-item" type="button"><a href="{% url 'currency:source-detail' src.id %}">Details</a></button>
          </div>
        </div>
       </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
 </div>
 <div>
  {% include 'includes/pagination.html' %}
</div>
{% endblock content %}

app/currency/templates/source_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
  Source update
{% endblock %}

{% block content %}
<p>
  {% if source.logo %}
    <th><img src="{{ source.logo.url }}" alt="logo" width="100px"></th>
  {% else %}
    <th>  <img src="{% static 'logo/logo.jpg' %}" alt="avatar" width="100px"></th>
  {% endif %}
</p>

Update Source Form
  
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button>Submit</button>
  </form>
{% endblock %}